version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: ppo_mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=tiny-es
    ports:
      - 27017:27017
    volumes:
      - ppo_mongo_data:/data/db
    networks:
      - ppo_netowrk

  postgresql:
    image: postgres:14
    container_name: ppo_postgres1
    restart: on-failure
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=tiny-es
    ports:
      - 5431:5432
    volumes:
      - ppo_postgres_data:/var/lib/postgresql/data
    networks:
      - ppo_netowrk

  task-manager:
    image: ppo_task_manager
    container_name: ppo_task_manager
    restart: on-failure
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - PROJECTION_DATABASE_URL=jdbc:postgresql://postgresql:5432/tiny-es
    build: .
    depends_on:
      - mongodb
      - postgresql
    ports:
      - 8080:8080
    networks:
      - ppo_netowrk

networks:
  ppo_netowrk:
    name: ppo_netowrk

volumes:
  ppo_mongo_data:
    name: ppo_mongo_data
  ppo_postgres_data:
    name: ppo_postgres_data
